### PR TITLE
Fixed import config

### PR DESCRIPTION
**Pull request by pielco11**

### CODE REVIEW

**Comment by Lonami** [comment]
Strange, I would swear the code had a `config = config['TelegramAPI']` which made this "redundancy" unnecessary…

**Comment by expectocode** [comment]
Yeah, it would probably be simpler to move that line up

**Comment by pielco11** [comment]
I think that doing `config = config['TelegramAPI']` may break `config['Dumper']`

**Comment by expectocode** [comment]
You are quite right :)

**Pull request merged**
